// ── Structured (JSON) Gemini call ────────────────────────────────────────────
// The chat route streams free-form text (streamGenerateContent + SSE). The Game
// Plan needs ONE structured object back, so this uses the non-streaming
// generateContent endpoint with responseMimeType:application/json + a
// responseSchema, plus the same overload-aware retry/backoff philosophy as chat.
// Errors carry a `code` so callers can map them to friendly HTTP responses.

// ── Model tiers (env-overridable so we can re-point without a deploy) ─────────
//   frontier — top-quality, used VERY sparingly (Deep Research Game Plan only,
//              and only once per stock per week thanks to the per-symbol cache).
//   value    — the workhorse for chat + everything else.
//   lite     — cheap, high-throughput backup for both.
// The ladder tries these in order, per key, falling through on "too busy".
export const frontierModel = () => process.env.GEMINI_FRONTIER_MODEL || "gemini-3.1-pro-preview";
export const valueModel = () => process.env.GEMINI_VALUE_MODEL || "gemini-3.5-flash";
export const liteModel = () => process.env.GEMINI_LITE_MODEL || "gemini-3.1-flash-lite";

// True only on a real production deploy. Everything else (local dev, staging,
// preview) is non-prod and must NOT spend on the paid flash/pro tiers.
export const isProductionEnv = () =>
  process.env.NODE_ENV === "production" ||
  process.env.APP_ENV === "production" ||
  process.env.PAYPAL_ENV === "live" ||
  !!process.env.RAILWAY_ENVIRONMENT;

// Outside production, collapse any model ladder to lite-only so testing never
// burns money on flash/pro. Set GEMINI_ALLOW_PAID_NONPROD=1 to opt back in.
export const paidTiersAllowed = () =>
  isProductionEnv() || process.env.GEMINI_ALLOW_PAID_NONPROD === "1";
// Friendly tier label for a resolved model id (for the "generated by" UI badge).
export function modelTier(model) {
  if (model === frontierModel()) return "frontier";
  if (model === valueModel()) return "value";
  if (model === liteModel()) return "lite";
  return "value";
}

// ── Thinking control ─────────────────────────────────────────────────────────
// Gemini 3.x exposes `thinkingLevel` ("minimal"|"low"|"medium"|"high"); the 2.5
// series instead takes a numeric `thinkingBudget`, and sending BOTH in one
// request is an error. Default thinking is "high" on 3.x Pro/Flash, and those
// thinking tokens bill at the full OUTPUT rate (response price = output + thinking
// tokens) — the single biggest cost driver — so each journey dials it down.
// Returns a thinkingConfig object to merge into generationConfig, or null when
// the model family is unknown or the level is a passthrough sentinel ("default"/
// "none"/anything unrecognized) — so we never send an invalid field.
const THINKING_LEVELS = ["minimal", "low", "medium", "high"];
// 3.x level → nearest 2.5 numeric budget (tokens). 0 = off (Flash/Lite only).
const LEVEL_TO_BUDGET = { minimal: 0, low: 1024, medium: 8192, high: 24576 };

export function thinkingConfigFor(model, level) {
  let lvl = THINKING_LEVELS.includes(level) ? level : null;
  if (!lvl || !model) return null;
  if (/gemini-3/.test(model)) {
    // 3.x Pro rejects "minimal" — clamp up to the lowest level it allows.
    if (lvl === "minimal" && /pro/.test(model)) lvl = "low";
    return { thinkingLevel: lvl };
  }
  if (/gemini-2\.5/.test(model)) {
    let budget = LEVEL_TO_BUDGET[lvl];
    if (budget === 0 && /pro/.test(model)) budget = 1024; // 2.5 Pro can't disable
    return { thinkingBudget: budget };
  }
  return null; // unknown family — don't risk an invalid field
}

// Desired thinking level per journey, env-overridable (set to "default" to leave
// the model at its built-in level). The levels reflect WHERE spend lives, not just
// per-call cost: chat runs every turn uncached, so that's where aggressive cuts pay
// off (low); the Game Plan is cached ~1 gen/stock/week on the premium frontier tier,
// so cutting it barely moves the bill but risks the premium output — keep it richer
// (medium); the lite trickle wants the cheapest — Flash-Lite already defaults to
// minimal, but we set it so re-pointing the lite model can't silently re-enable
// thinking.
export function chatThinkingLevel() {
  return process.env.ORI_CHAT_THINKING_LEVEL || "low";
}
export function gamePlanThinkingLevel() {
  return process.env.GAME_PLAN_THINKING_LEVEL || "medium";
}
export function liteThinkingLevel() {
  return process.env.GEMINI_LITE_THINKING_LEVEL || "minimal";
}

const genUrl = (model) =>
  `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`;
const REQUEST_TIMEOUT_MS = 30000; // don't let a hung LLM call tie up the request + rate-limit slot

// Cap concurrent structured (game-plan / intangibles) Gemini calls. These are now
// generated on demand (a user opening a Deep Research Game Plan), but several can
// still land at once across users; without a ceiling they fan out into many
// simultaneous requests that trip 429/503 "overloaded" — and, because chat shares
// the same key + quota, that also makes interactive Ori "too busy". This gate
// keeps the structured path to a trickle so the streaming chat path stays clear.
// A waiter inherits the releasing call's slot, so `active` never exceeds the cap.
const MAX_CONCURRENT = 2;
let active = 0;
const waiters = [];
function acquireSlot() {
  if (active < MAX_CONCURRENT) {
    active++;
    return Promise.resolve();
  }
  return new Promise((resolve) => waiters.push(resolve));
}
function releaseSlot() {
  const next = waiters.shift();
  if (next) next();   // hand the slot straight to the next waiter (active unchanged)
  else active--;
}
// "Move to the next model/key" cases: rate-limited / overloaded (429/503/5xx),
// OR 404 (a model id this key can't serve — e.g. a preview not enabled), so an
// unavailable frontier model falls through to value→lite gracefully.
const failover = (status, body) =>
  status === 429 || status === 503 || status === 404 ||
  (status >= 500 && /unavailable|overloaded|try again/i.test(body || ""));

function err(message, code, extra = {}) {
  const e = new Error(message);
  e.code = code;
  Object.assign(e, extra);
  return e;
}

// Ordered list of usable Gemini keys: primary, then an optional backup we fail
// over to when the primary is "too busy" (429/503). Shared by the chat path so
// both behave the same. NOTE: a backup only adds real headroom if it belongs to
// a DIFFERENT Google Cloud project — Gemini quota is per-project, not per-key.
export function geminiKeys() {
  const ok = (k) => k && k !== "your_gemini_api_key_here";
  return [process.env.GEMINI_API_KEY, process.env.GEMINI_API_KEY_BACKUP].filter(ok);
}

/**
 * Generate a structured JSON object from Gemini, walking a model+key ladder.
 * Tries every model (in order) on the PRIMARY key, then the same models on the
 * BACKUP key, failing over on each "too busy"/unavailable response. Returns the
 * parsed object plus the model id that actually produced it (for display).
 * @param {object}  opts
 * @param {string}  opts.system   system instruction
 * @param {string}  opts.prompt   user prompt
 * @param {object}  opts.schema   Gemini responseSchema (UPPERCASE OpenAPI types)
 * @param {number} [opts.temperature]
 * @param {string[]} [opts.models]   per-key model ladder, tried on every key (default value→lite)
 * @param {string}  [opts.leadModel] a scarce model (e.g. frontier) tried ONCE, on the primary key
 *                                    only, ahead of the per-key ladder — so its quota is never
 *                                    spent twice in one generation.
 * @param {string}  [opts.thinkingLevel] "minimal"|"low"|"medium"|"high" — applied per model via
 *                                    thinkingConfigFor (3.x thinkingLevel / 2.5 thinkingBudget).
 * @returns {Promise<{ data: object, model: string, usage: object|null }>}
 * @throws  Error with .code: "no_key" | "overloaded" | "bad_json" | "error"
 */
export async function geminiGenerateJson({
  system,
  prompt,
  schema,
  temperature = 0.45,
  models,
  leadModel,
  maxOutputTokens = 2000,
  cachedContent = null,
  getCachedContent = null,
  thinkingLevel = null,
}) {
  const keys = geminiKeys();
  if (!keys.length) throw err("GEMINI_API_KEY not configured", "no_key");
  let ladder = models && models.length ? models : [valueModel(), liteModel()];
  let lead = leadModel;
  // Non-prod test cost guard: lite only, and drop the frontier/value lead.
  if (!paidTiersAllowed()) {
    ladder = [liteModel()];
    lead = null;
  }

  // Ordered (key, model) attempts: lead once on the primary key, then the
  // ladder on the primary key, then the ladder on the backup key.
  const combos = [];
  if (lead) combos.push({ apiKey: keys[0], model: lead });
  for (const apiKey of keys) for (const model of ladder) combos.push({ apiKey, model });

  const baseBody = {
    contents: [{ role: "user", parts: [{ text: prompt }] }],
    generationConfig: {
      responseMimeType: "application/json",
      responseSchema: schema,
      temperature,
      maxOutputTokens,
    },
  };

  await acquireSlot();
  try {
    return await runLadder(baseBody, combos, { system, cachedContent, getCachedContent, thinkingLevel });
  } finally {
    releaseSlot();
  }
}

function bodyForModel(baseBody, model, { system, cachedContent, getCachedContent, thinkingLevel }) {
  const body = { ...baseBody, contents: baseBody.contents.map((c) => ({ ...c, parts: c.parts.map((p) => ({ ...p })) })) };
  const cacheName = getCachedContent?.(model) || cachedContent || null;
  if (cacheName) {
    body.cachedContent = cacheName;
  } else if (system) {
    body.systemInstruction = { parts: [{ text: system }] };
  }
  // Per-model thinking control (3.x level / 2.5 budget). Fresh generationConfig
  // only when it applies, so the shared baseBody.generationConfig is never mutated.
  const tc = thinkingConfigFor(model, thinkingLevel);
  if (tc) body.generationConfig = { ...baseBody.generationConfig, ...tc };
  return body;
}

async function runLadder(baseBody, combos, cacheOpts = {}) {
  let lastStatus = 0;
  {
    for (const { apiKey, model } of combos) {
      const body = bodyForModel(baseBody, model, cacheOpts);
      let res;
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);
      try {
        res = await fetch(genUrl(model), {
          method: "POST",
          headers: { "Content-Type": "application/json", "X-goog-api-key": apiKey },
          body: JSON.stringify(body),
          signal: controller.signal,
        });
      } catch {
        continue; // network error / timeout abort — try the next model/key
      } finally {
        clearTimeout(timer);
      }

      if (res.ok) {
        const data = await res.json();
        const text = (data?.candidates?.[0]?.content?.parts || []).map((p) => p.text || "").join("");
        if (!text) throw err("Ori returned an empty response", "bad_json");
        try {
          // usage carries Gemini's token accounting (incl. cachedContentTokenCount)
          // so callers can meter cost and the context-cache hit rate.
          return { data: JSON.parse(text), model, usage: data.usageMetadata || null };
        } catch {
          throw err("Ori returned malformed JSON", "bad_json");
        }
      }

      const bodyText = await res.text();
      lastStatus = res.status;
      if (failover(res.status, bodyText)) continue; // busy / unavailable — next combo
      throw err(`Gemini error ${res.status}`, "error", { status: res.status });
    }
  }
  throw err("Gemini error: all models/keys busy", "overloaded", { status: lastStatus });
}
