// S&P 500 + S&P 400 MidCap + S&P 600 SmallCap + popular additions — ~2500 symbols
export const UNIVERSE = [
  // ── S&P 500 ──────────────────────────────────────────────────────────────
  'MMM','AOS','ABT','ABBV','ACN','ADBE','AMD','AES','AFL','A','APD','ABNB','AKAM','ALB','ARE','ALGN',
  'ALLE','LNT','ALL','GOOGL','GOOG','MO','AMZN','AMCR','AEE','AAL','AEP','AXP','AIG','AMT','AWK',
  'AMP','AME','AMGN','APH','ADI','ANSS','AON','APA','AAPL','AMAT','APTV','ACGL','ADM','ANET','AJG',
  'AIZ','T','ATO','ADSK','ADP','AZO','AVB','AVY','AXON','BKR','BALL','BAC','BK','BBWI','BAX',
  'BDX','BBY','BIO','TECH','BIIB','BLK','BX','BA','BCR','BSX','BMY','AVGO','BR','BRO','BF.B',
  'BG','CDNS','CZR','CPT','CPB','COF','CAH','KMX','CCL','CARR','CTLT','CAT','CBOE','CBRE','CDW',
  'CE','COR','CNC','CNX','CDAY','CF','CRL','SCHW','CHTR','CVX','CMG','CB','CHD','CI','CINF','CTAS',
  'CSCO','C','CFG','CLX','CME','CMS','KO','CTSH','CL','CMCSA','CMA','CAG','COP','ED','STZ','CPRT',
  'GLW','CTVA','CSGP','COST','CTRA','CCI','CSX','CMI','CVS','DHR','DHI','DRI','DVA','DAY','DE','DAL',
  'XRAY','DVN','DXCM','FANG','DLR','DFS','DG','DLTR','D','DPZ','DOV','DOW','DHC','DTE','DUK','DD',
  'EMN','ETN','EBAY','ECL','EIX','EW','EA','ELV','LLY','EMR','ENPH','ETR','EOG','EPAM','EQT','EFX',
  'EQIX','EQR','ESS','EL','ETSY','EG','EVRG','ES','EXC','EXPE','EXPD','EXR','XOM','FFIV','FDS',
  'FICO','FAST','FRT','FDX','FIS','FITB','FSLR','FE','FI','FMC','F','FTNT','FTV','FOXA','FOX',
  'BEN','FCX','GRMN','IT','GE','GEHC','GEV','GEN','GNRC','GD','GIS','GM','GPC','GILD','GS','HAL',
  'HIG','HAS','HCA','DOC','HSIC','HSY','HES','HPE','HLT','HOLX','HD','HON','HRL','HST','HWM',
  'HPQ','HUBB','HUM','HBAN','HII','IBM','IEX','IDXX','ITW','INCY','IR','PODD','INTC','ICE','IFF',
  'IP','IPG','INTU','ISRG','IVZ','INVH','IQV','IRM','JBHT','JBL','JKHY','J','JNJ','JCI','JPM',
  'JNPR','K','KVUE','KDP','KEY','KEYS','KMB','KIM','KMI','KLAC','KHC','KR','LHX','LH','LRCX',
  'LW','LVS','LDOS','LEN','LIN','LYV','LKQ','LMT','L','LOW','LULU','LYB','MTB','MRO','MPC','MKTX',
  'MAR','MMC','MLM','MAS','META','MET','MTD','MGM','MCHP','MU','MSFT','MAA','MRNA','MHK','MOH',
  'TAP','MDLZ','MPWR','MNST','MCO','MS','MOS','MSI','MSCI','NDAQ','NTAP','NFLX','NEM','NWSA',
  'NWS','NEE','NKE','NI','NDSN','NSC','NTRS','NOC','NCLH','NRG','NUE','NVDA','NVR','NXPI','ORLY',
  'OXY','ODFL','OMC','ON','OKE','ORCL','OTIS','PCAR','PKG','PANW','PH','PAYX','PAYC','PYPL','PNR',
  'PEP','PFE','PCG','PM','PSX','PNW','PXD','PNC','POOL','PPG','PPL','PFG','PG','PGR','PRU','PEG',
  'PTVE','PTC','PSA','PHM','QRVO','PWR','QCOM','DGX','RL','RJF','RTX','O','REG','REGN','RF','RSG',
  'RMD','RVTY','ROK','ROL','ROP','ROST','RCL','SPGI','CRM','SBAC','SLB','STX','SEE','SRE','NOW',
  'SHW','SPG','SWKS','SJM','SW','SNA','SOLV','SO','LUV','SWK','SBUX','STT','STLD','STE','SYK',
  'SMCI','SYF','SNPS','SYY','TMUS','TROW','TTWO','TPR','TGT','TEL','TDY','TFX','TER','TSLA','TXN',
  'TXT','HAS','TMO','TJX','TSCO','TT','TDG','TRV','TRMB','TFC','TYL','TSN','USB','UBER','UDR',
  'ULTA','UNP','UAL','UPS','URI','UNH','UHS','VLO','VTR','VLTO','VRSN','VRSK','VZ','VRTX','VFC',
  'VTRS','VICI','V','VMC','WRB','GWW','WAB','WBA','WMT','DIS','WBD','WM','WAT','WEC','WFC','WELL',
  'WST','WDC','WHR','WMB','WTW','WYNN','XEL','XYL','YUM','ZBRA','ZBH','ZTS',
  // ── Nasdaq 100 extras ─────────────────────────────────────────────────────
  'DDOG','TEAM','ZS','SNOW','CRWD','NET','MDB','HUBS','WDAY','VEEV','OKTA','ZI','BILL',
  'U','RBLX','HOOD','COIN','SQ','SHOP','MELI','SE','PDD','BIDU','BABA','JD','NIO','XPEV','LI',
  'RIVN','LCID','PLTR','AI','SOUN','PATH','IONQ','ASAN','FROG','DOCN','GTLB','CFLT',
  'ESTC','APPN','BOX','TWLO','DOCU','DBX','WIX','MNDY','DASH','DKNG','LYFT','SNAP','SOFI',
  'AFRM','UPWK','BRZE','DUOL','TOST','PSTG','NTNX','OLO','WK','ZD','KVYO','CAVA','RXRX',
  'CART','BIRK','ARM','INST','RKLB','ASTS','ACHR',
  // ── S&P 400 MidCap ───────────────────────────────────────────────────────
  'ACHC','ACIW','ACM','ADNT','ALEX','ALK','ALLE','ALRM','ALTR','AMG','AMKR','AMNB','AMPH','AMR',
  'AMRC','ANF','APLE','APPF','ARC','ARCB','ARCO','ARGX','ARI','ARW','ASH','ASO','ATGE','ATKR',
  'ATR','ATRC','AU','AVNT','AVTR','AWI','AX','AYI','AZEK','BCO','BDC','BECN','BHF','BJ','BKI',
  'BLKB','BPOP','BRC','BRKR','BRX','BVS','BWA','BXMT','BYD','CABO','CACC','CADE','CAKE','CALM',
  'CAMT','CARG','CBT','CCCS','CCEP','CEIX','CENX','CHE','CHRD','CIB','CIEN','CNK','CNMD','CNO',
  'COHR','COLM','CONE','COOP','CRI','CRUS','CROX','CVLT','CWK','CWT','CWST','DAR','DLB','DLX',
  'DNB','DOCS','DRH','DT','DXC','EFC','EGP','EHC','ENOV','ENS','EPRT','ESE','EVTC','EXP','FAF',
  'FBP','FELE','FFIN','FHI','FHN','FIBK','FLO','FLR','FORM','FPH','FRME','FRPT','FSS','FUL',
  'GATX','GFF','GKOS','GMS','GNTX','GOLF','GPK','GPI','GRBK','GTN','GTY','HAE','HAFC','HASI',
  'HAYW','HBI','HBT','HCSG','HGV','HLIT','HOMB','HP','HPCO','HRI','HRB','HRMY','HTH','HWKN',
  'IART','IBP','ICUI','IIIN','IOSP','IRDM','ITGR','ITT','JHG','JLL','KAR','KBH','KFY','KLIC',
  'KNF','KSS','LANC','LBRT','LCII','LGIH','LNN','LNTH','LPLA','LRN','LSI','LSTR','LTC','LUNR',
  'MAC','MANT','MATX','MBI','MCY','MDGL','MDU','MEDP','MHO','MKL','MKSI','MLI','MMI','MMSI',
  'MNRO','MOD','MORN','MPW','MRC','MTH','MTSI','MUR','NBR','NBTB','NCR','NEO','NEOG','NNN','NVT',
  'OFG','OGE','OGS','OHI','OI','OII','OLN','ORA','OSK','OUT','PMT','POST','PRGO','PRIM','PRI',
  'PRK','PVH','RBC','REZI','RGA','RMBS','RNR','RPM','RYN','SAFE','SAM','SANM','SBCF','SBH',
  'SBSI','SCCO','SCSC','SEM','SF','SIGI','SIX','SKY','SM','SMG','SPNC','SPR','SRC','SRCL',
  'SSNC','STRA','SUM','SUPN','SVC','SWX','TDC','TFIN','THO','TKR','TLYS','TMHC','TPH','TR',
  'TRMK','TRN','TWNK','TXG','TXRH','UE','UNIT','UPBD','URBN','VCEL','VCTR','VGR','VIRT','VMEO',
  'VRTS','VSH','VSTO','WAFD','WERN','WSFS','WTFC','WTS','WW','WWW','XNCR','XPEL','YETI','ZWS',
  // ── S&P 600 SmallCap ─────────────────────────────────────────────────────
  'AAON','ABCB','ABG','ABM','ACC','ACNB','AEO','AGYS','AHH','AIN','AIT','AKR',
  'ALGT','ALKS','ALRM','ALX','AMBC','AMCX','ANIK','AOSL','APAM','APG','APOG',
  'ARNC','AROW','ARWR','ASTE','ATEN','ATI','ATNI','ATRI','ATRO','ATSG','AUB',
  'AUDC','AUPH','AVA','AVAV','AVNW','AVT','AXGN','AXS','AXTA','AZZ','BANF',
  'BANR','BDN','BFS','BGS','BHLB','BJRI','BLX','BOOT','BRT','BTU','BWXT','BXC',
  'CAR','CASH','CATO','CBT','CEVA','CGNX','CHX','CLF','CLH','CLW','CMC','CMCO',
  'CMO','COHU','COLB','CORT','CPS','CRC','CSL','CSWI','CTG','CTO','CVBF','CVCO',
  'CWH','DCO','DENN','DFH','DGII','DIN','DLX','DRH','DXPE','ECPG','EFC','EIG',
  'ENOV','ENR','ENS','ENVX','EPR','ESE','ESNT','EXP','FARO','FFBC','FHB',
  'FLO','FPH','FRME','FRPT','FSS','FUL','GKOS','GMS','GPK','GPI','GRBK','GTY',
  'HASI','HAYW','HBI','HBT','HCSG','HGV','HLIT','HOMB','HRI','HRB','HTH','HWKN',
  'IIIN','KAR','KBH','KFY','KLIC','KNF','KSS','LANC','LBRT','LCII','LGIH',
  'LNN','LSTR','LTC','MANT','MATX','MEDP','MHO','MKSI','MLI','MMI','MMSI','MOD',
  'MORN','MRC','MTH','MTSI','MUR','NBTB','NEO','NEOG','NVT','OFG','OGE','OGS',
  'OHI','OI','OII','OLN','ORA','OSK','PMT','PRGO','PRIM','PRI','PRK','RBC',
  'REZI','RGA','RMBS','RNR','RPM','RYN','SANM','SBCF','SBH','SCSC','SEM','SIGI',
  'SKY','SM','SPR','SRC','SRCL','SSNC','STRA','SUM','SUPN','SVC','SWX','THO',
  'TKR','TMHC','TPH','TRMK','TRN','TWNK','URBN','VCEL','VCTR','VGR','VIRT',
  'VRTS','VSH','WERN','WSFS','WTFC',
  // ── REITs (broader) ───────────────────────────────────────────────────────
  'ADC','AIRC','BDN','BXP','CHCT','COLD','CPT','CXW','DEA','DEI','EGP','ELME',
  'EPR','EPRT','EQR','ESS','EXR','GLPI','HIW','HPP','IIPR','INVH','IRET','JBGS',
  'KREF','KRG','KW','LAND','LTC','LXP','MAA','NHI','NNN','NSA','NXRT','PEAK',
  'PLD','REXR','RHP','RITM','RLJ','RPT','RTL','SAFE','SHO','SLG','STAG','STOR',
  'STWD','TRNO','TRTX','UDR','VICI','VNO','VTR','WD','WELL','WPC','WY','XHR',
  // ── Utilities ────────────────────────────────────────────────────────────
  'ALE','AVA','BEP','BEPC','BKH','CPK','CWT','DTE','EVRG','HE','IDA','MGEE',
  'NI','NJR','NWE','NWN','OTTR','PNM','PNW','PPL','SJW','UGI','WGL','WEC',
  // ── Energy (E&P, midstream, services) ────────────────────────────────────
  'AR','AESI','BSM','CIVI','CNXC','CPE','CRK','CVI','DEN','DINO','DKL',
  'ENLC','EPD','ET','GPOR','HES','HLX','HPK','KOS','LNG','MRO','MTDR',
  'NOG','NOV','NR','OVV','PDC','PDCE','PTEN','RES','RRC','SDRL','SMLP',
  'STNG','TELL','TEN','TUSK','WRK',
  // ── Financials (regional banks, insurance, asset mgmt) ───────────────────
  'ASB','AUB','BANC','BANF','BANR','BKU','BOKF','BPFH','BPOP','BRKL','BSVN',
  'BUSE','CBSH','CFB','CFFI','CHMG','CLBK','CLNB','CNB','CNOB','COFI','COLB',
  'CPF','DCOM','EWBC','FCB','FCBP','FCCO','FCNCA','FHB','FHI','FISI','FMCB',
  'FNB','FULT','GABC','GBCI','GNTY','GWB','HAFC','HBAN','HBCP','HFWA','HMST',
  'HOMB','HTBK','HTLF','IBCP','IBOC','IBTX','INDB','ISBA','KBAL','KRNY','LARK',
  'LBAI','LKFN','MBWM','MFNC','MOFG','NBHC','NBTB','NKSH','NWBI','NYCB',
  'OCFC','OPBK','OVBC','PACW','PBCT','PFBC','PFIS','PKBK','PLBC','PNFP','PPBI',
  'PVBC','QCRH','RBNC','RNST','SASR','SBFG','SBSI','SEIC','SFBS','SFNC','SFST',
  'SMBC','SMBK','TCBI','TCBK','TBNK','TFIN','TOWN','TRMK','UMBF','UVSP','WAL',
  'WASH','WSBC','WTFC','ZION',
  // ── Healthcare / Medtech / Pharma ─────────────────────────────────────────
  'ACAD','ACVA','AGIO','AKBA','ALNY','AMRX','ANAB','APLT','ARDX','ARGX',
  'ARMO','ARQT','ARWR','ASND','ATRC','ATRS','ATXI','AUPH','AVDL','AVEO',
  'AVID','AVRO','AVTE','AVXL','AXSM','BEAM','BHVN','BLUE','BMRN','CELC',
  'CERE','CGEN','CLDX','CMRX','CRSP','EDIT','EXEL','FATE','FOLD','GH',
  'HALO','HZNP','ICRR','IDYA','IMVT','INSP','INSM','INVA','IONS','IRTC',
  'ISEE','ITCI','JAZZ','KALV','KRYS','KYMR','LGND','LHCG','MDGL','MGNX',
  'MIRM','MORF','NKTR','NOVA','NUVL','NVST','OGN','OLMA','OMCL','ONEM',
  'PACB','PGNY','PRLD','QURE','RARE','RCKT','RGEN','ROIV','RVMD','RXRX',
  'SAGE','SANA','SDGR','SILK','SMMT','SRPT','STRO','SWAV','TGTX','TWST',
  'VERA','VRDN','XENE','ZLAB','ZNTL','AMPH','AMRX','ANIK','AXNX','BDSX',
  'BNTX','NVAX','MDT','CSTE','ARIS','ECVT','QDEL','RCKT','INSP','NVST',
  // ── Consumer discretionary additions ─────────────────────────────────────
  'BURL','FIVE','HIBB','OLLI','PLAY','PRPL','RUTH','BLMN','EAT','JACK',
  'RRGB','SHAK','WING','NATH','DNKN','LOCO','CBRL','MCD','WEN','QSR',
  'SFM','SPTN','WEIS','WOOF','PETQ','FDP','HBI','HIMS','CONN','TLRD',
  'CPRI','GPS','DKS','HIBB','DECK','SKX','COLM','VFC','LEVI','BOOT',
  // ── Technology additions ──────────────────────────────────────────────────
  'ACLS','AEHR','ALGM','AOSL','APIO','APLD','CCOI','CNXN','COHU','CRUS',
  'DIOD','EMKR','EXTR','FOUR','GDDY','GWRE','HALO','JFROG','LSPD','MDLA',
  'NTNX','NVST','OPRA','PEGA','PLTK','QTWO','RPAY','SEMR','SMAR','TTGT',
  'UHAL','VRNS','UPWK','WIRE','EGHT','BAND','APPN','BKNG',
  // ── International ADRs ───────────────────────────────────────────────────
  'ASML','TSM','BABA','JD','PDD','BIDU','NIO','XPEV','LI','NTES','RLX',
  'CAN','MNSO','KE','XP','STNE','VIST','ITUB','BBD','VALE','PBR','ERJ',
  'GOLD','TECK','CS','UBS','DB','SAN','HSBC','BCS','LYG','VOD','BP',
  'SHEL','TTE','EQNR','E','STM','MT','ABB','TD','RY','BNS','CM','ENB',
  'SU','CNQ','CP','TRP','BAM','MFC','SLF','BCE','ATD','CCO','IMO','CVE',
  'AEM','LUN','HBM','AGI','DESP','GFI','SBSW','GLPG','CNHI','HEIA',
  'GIVN','LONN','LISN','VACN','TEMN','NOVN','ROG','SREN','ABBN','UBSG',
  'TAL','EDU','WB','IQ','BILI','HTHT','YMM','BOSS','PAGS','IDB','GGB',
  'SUZ','IAG','SID','BSAC','CIG','ABEV','BSMX','GGAL','BMA','CEPU',
  'LOMA','SUPV','IRCP','CAAP','VNET','HOLI','DAVA','ATHM','TIGR',
  'WPM','PAAS','KGC','RIO','BHP','MKC','UL','H','XPO','SAIA','CHRW',
  'NOV','DISH','SATS','BNTX','NVAX',
  // ── Industrials & Materials ───────────────────────────────────────────────
  'AMWD','AOS','ARCB','ARNC','ATI','ATR','ATRO','ATSG','AZZ','BANR','BXC',
  'CAR','CBT','CLF','CLH','CMC','CMCO','CSL','DAR','DCO','ENOV','ENR',
  'EXP','FARO','FSS','FUL','GATX','GFF','GMS','GNTX','GPK','GPI','HAE',
  'HWKN','ITT','KAR','KLIC','LANC','LBRT','MLI','MRC','MTSI','MUR',
  'NBTB','OII','OLN','ORA','OSK','PRK','RBC','RPM','RYN','SAM','SANM',
  'SEM','SKY','SM','SPR','SRC','SRCL','SSNC','SWX','THO','TKR',
  'TR','TRMK','TRN','VCTR','VGR','VSH','WAFD','WERN','WWW',
].filter((v, i, a) => a.indexOf(v) === i); // dedupe
